title: WhatsAuth Developers Docs
description: A starter hub for creating solutions with WhatsAuth
theme: just-the-docs

url: https://lets-talk.github.io/whatsauth-docs

# Color scheme supports "light" (default) and "dark"
color_scheme: light

aux_links:
  "Go to App": https://app.whatsauth.com/?utm_source=nav-bar-docs

ga_tracking: "G-R2KM91VYC2"

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"
# callouts
callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "10.4.0"